// Indian job-hub cities supported by the scraper (mirrors backend/app/cities.py).
export const INDIAN_CITIES: string[] = [
  'Bengaluru',
  'Mumbai',
  'Delhi NCR',
  'Hyderabad',
  'Chennai',
  'Pune',
  'Kolkata',
  'Ahmedabad',
  'Gurugram',
  'Noida',
  'Jaipur',
  'Lucknow',
  'Chandigarh',
  'Kochi',
  'Coimbatore',
  'Indore',
  'Bhopal',
  'Nagpur',
  'Surat',
  'Vadodara',
  'Thiruvananthapuram',
  'Bhubaneswar',
  'Visakhapatnam',
  'Mysuru',
  'Dehradun',
  'Guwahati',
  'Patna',
  'Ranchi',
  'Jodhpur',
  'Vijayawada',
]

export const DEFAULT_CITY = 'Bengaluru'
